//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetki
    {
        public Yetki()
        {
            this.UyeTabloes = new HashSet<UyeTablo>();
        }
    
        public int YetkiId { get; set; }
        public string Yetkisi { get; set; }
    
        public virtual ICollection<UyeTablo> UyeTabloes { get; set; }
    }
}
